name: Admin Edit Index

on:
  workflow_dispatch:
    inputs:
      content:
        description: "Isi index.html"
        required: true
        type: string

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update index.html
        run: |
          cat > index.html <<'EOF'
          ${{ inputs.content }}
          EOF

      - name: Commit perubahan
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Update undangan dari Admin"
          git push
